version: "3.8"

services:
  nextjs-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000" # Map to a different external port
    volumes:
      - .:/app
      - /app/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wander-dev.rule=Host(`dev-wander.localhost`)"
      - "traefik.http.services.wander-dev.loadbalancer.server.port=3000"
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - traefik-network

  nextjs-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000" # Use a different port for production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wander-prod.rule=Host(`prod-wander.localhost`)"
      - "traefik.http.services.wander-prod.loadbalancer.server.port=3000"
    environment:
      NODE_ENV: production
    command: npm run start
    networks:
      - traefik-network

networks:
  traefik-network:
    external: true
