import { BusinessListing } from "../types/BusinessListing";

export const initializeBusinessForm = (): Partial<BusinessListing> => ({
  businessId: "",
  addressDetails: {
    id: 0,
    userId: "",
    businessId: "",
    businessName: "",
    buildingName: "",
    floorNumber: "",
    street: "",
    city: "",
    country: "",
    county: "",
    postcode: "",
    latitude: 0,
    longitude: 0,
    createdAt: "",
    updatedAt: "",
  },
  contactDetails: {
    id: 0,
    userId: "",
    businessId: "",
    businessName: "",
    primaryContactFirstName: "",
    primaryContactLastName: "",
    contactEmail: "",
    contactNumber: "",
    websiteUrl: "",
    createdAt: "",
    updatedAt: "",
  },
  businessSpecs: {
    id: 0,
    userId: "",
    businessId: "",
    businessName: "",
    description: "",
    createdAt: "",
    updatedAt: "",
  },
  createdAt: "",
  updatedAt: "",
});
